# NumPy شرح عميق + أمثلة كتير (بالعربي)
الـ Notebook ده معمول عشان تفهم NumPy **فهم حقيقي** مش حفظ.
كل جزء:
- شرح نظري بسيط
- مثال
- مثال عملي أقرب للشغل الحقيقي


## 1️⃣ Import NumPy

In [2]:
import numpy as np

## 2️⃣ إنشاء NumPy Arrays
الـ ndarray هو الهيكل الأساسي في NumPy.
- أسرع من الـ list
- بيستخدم Memory أقل
- بيشتغل Vectorized


In [3]:

a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4]])
a, b


(array([1, 2, 3, 4]),
 array([[1, 2],
        [3, 4]]))

## 3️⃣ Dimensions & Shape
- ndim : عدد الأبعاد
- shape : شكل المصفوفة


In [4]:

print(a.ndim)
print(b.ndim)
print(b.shape)


1
2
(2, 2)


## 4️⃣ Reshape (مهم جدًا)
بنغير شكل الداتا **من غير ما نغير القيم**
شرط أساسي: عدد العناصر يفضل ثابت


In [5]:

x = np.arange(12)
x.reshape(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### مثال حقيقي
صورة grayscale 1D → 2D


In [6]:

image = np.arange(16)
image.reshape(4,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 5️⃣ Dtype
كل Array ليه نوع بيانات واحد فقط
ولو دخلت أنواع مختلفة → NumPy هيختار النوع الأوسع


In [7]:

arr = np.array([1, 2.5, 3])
arr.dtype


dtype('float64')

### تغيير النوع

In [8]:

arr_int = arr.astype(int)
arr_int


array([1, 2, 3])

## 6️⃣ Indexing & Slicing
نفس فكرة الـ list بس أقوى


In [9]:

mat = np.array([[10,20,30],[40,50,60]])
mat[0, 1]      # عنصر
mat[:, 1]      # عمود كامل
mat[1, :]      # صف كامل


array([40, 50, 60])

## 7️⃣ Quick Array Creation
تستخدمها كتير في ML و DL


In [10]:

np.zeros((3,3))
np.ones((2,4))
np.full((2,2), 9)
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 8️⃣ arange vs linspace
- arange → step
- linspace → عدد عناصر


In [11]:

np.arange(0, 10, 2)
np.linspace(0, 10, 5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## 9️⃣ Random (مهم في التجارب)


In [12]:

np.random.random((2,2))
np.random.randint(1, 100, (3,3))


array([[75, 71, 76],
       [ 3, 57, 72],
       [10, 46, 30]], dtype=int32)

## 🔟 NPZ Files (حفظ وتحميل)
مهم جدًا في المشاريع


In [13]:

a = np.array([1,2,3])
b = np.array([4,5,6])

np.savez("data.npz", arr1=a, arr2=b)

loaded = np.load("data.npz")
loaded["arr1"], loaded["arr2"]


(array([1, 2, 3]), array([4, 5, 6]))

## 1️⃣1️⃣ Stacking
دمج داتا من مصادر مختلفة


In [14]:

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.vstack((a,b))
np.hstack((a,b))


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## 1️⃣2️⃣ Comparison
بيطلع Boolean Array


In [15]:

x = np.array([1,2,3])
y = np.array([1,2,4])

x == y
np.all(x == y)
np.any(x == y)


np.True_

## 1️⃣3️⃣ Conditional Access & Modification
ده أساس Data Cleaning


In [16]:

data = np.array([10, -5, 20, -1])
data[data < 0] = 0
data


array([10,  0, 20,  0])

## 1️⃣4️⃣ Broadcasting (قوة NumPy)
عمليات بين Shapes مختلفة


In [17]:

mat = np.array([[1,2,3],[4,5,6]])
mat + 10


array([[11, 12, 13],
       [14, 15, 16]])

## 1️⃣5️⃣ Sparse Matrix (فكرة)
بنخزن القيم المهمة بس


In [18]:

from scipy.sparse import csr_matrix

dense = np.array([[0,0,5],[0,3,0]])
csr_matrix(dense)


<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (2, 3)>